version: '3'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: grid_test_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grid_test_db